"""initial schema

Revision ID: 2a92775f145c
Revises: 
Create Date: 2026-09-21 04:25:24.377901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a92775f145c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stable_id', sa.String(length=100), nullable=False),
    sa.Column('challenge_type', sa.Enum('phishing', 'logs', 'decode', name='challengetype'), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stable_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.Enum('draft', 'open', 'paused', 'closed', name='eventstate'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('active_ruleset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'route', 'key', name='uq_idempotency_scope_route_key')
    )
    op.create_table('challenge_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('public_data', sa.JSON(), nullable=False),
    sa.Column('private_validator', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'revision', name='uq_challenge_revision')
    )
    op.create_table('kiosks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('credential_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rulesets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('hint_penalty', sa.Integer(), nullable=False),
    sa.Column('base_points', sa.Integer(), nullable=False),
    sa.Column('wrong_attempt_penalty', sa.Integer(), nullable=False),
    sa.Column('capture_bonus', sa.Integer(), nullable=False),
    sa.Column('qualification_solves_required', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('ruleset_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_type', sa.Enum('phishing', 'logs', 'decode', name='challengetype'), nullable=False),
    sa.Column('pool', sa.JSON(), nullable=False),
    sa.Column('consumed', sa.JSON(), nullable=False),
    sa.Column('last_assigned_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('kiosk_id', sa.String(length=36), nullable=False),
    sa.Column('ruleset_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('publish_consent', sa.Boolean(), nullable=False),
    sa.Column('accessibility_mode', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Enum('ready', 'active', 'completed', 'expired', 'abandoned', name='gamesessionstate'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('solved_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('recovery_credential_hash', sa.String(length=255), nullable=True),
    sa.Column('idempotency_salt', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('pending', 'qualified', 'unqualified', name='entitlementstate'), nullable=False),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('challenge_revision_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('pending', 'solved', 'failed', 'skipped', name='outcome'), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('awarded_points', sa.Integer(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_revision_id'], ['challenge_revisions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_session_position')
    )
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_challenge_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('answer_summary', sa.String(length=500), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['session_challenge_id'], ['session_challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_challenge_id', 'ordinal', name='uq_attempt_ordinal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    op.drop_table('session_challenges')
    op.drop_table('entitlements')
    op.drop_table('game_sessions')
    op.drop_table('challenge_pools')
    op.drop_table('rulesets')
    op.drop_table('kiosks')
    op.drop_table('challenge_revisions')
    op.drop_table('idempotency_records')
    op.drop_table('events')
    op.drop_table('challenges')
    # ### end Alembic commands ###
